-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 18:51:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CRS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS CRS ;

-- -----------------------------------------------------
-- Schema CRS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS CRS DEFAULT CHARACTER SET utf8 ;
USE CRS ;

-- -----------------------------------------------------
-- Table `CRS`.`고객`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`고객` ;

CREATE TABLE IF NOT EXISTS CRS.`고객`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`상품`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`상품` ;

CREATE TABLE IF NOT EXISTS CRS.`상품`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `이름` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `CRS`.`PNR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`PNR` ;

CREATE TABLE IF NOT EXISTS CRS.`PNR`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `고객_ID` INT NOT NULL,
  `상품_ID` INT NOT NULL,
  `예약일자` DATETIME NULL,
  INDEX `fk_PNR_고객1_idx` (`고객_ID` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  INDEX `fk_PNR_상품1_idx` (`상품_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PNR_고객1`
    FOREIGN KEY (`고객_ID`)
    REFERENCES CRS.`고객` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNR_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`성별_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`성별_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`성별_코드`(
  `CODE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`국적코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`국적코드` ;

CREATE TABLE IF NOT EXISTS CRS.`국적코드`(
  `코드` INT NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`체류지_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`체류지_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`체류지_코드`(
  `코드` INT NOT NULL,
  `국적코드` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`, `국적코드`),
  INDEX `fk_체류지 코드_국적코드1_idx` (`국적코드` ASC) VISIBLE,
  CONSTRAINT `fk_체류지 코드_국적코드1`
    FOREIGN KEY (`국적코드`)
    REFERENCES CRS.`국적코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`연령_구분_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`연령_구분_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`연령_구분_코드`(
  `ID` INT NOT NULL,
  `연령 구분` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`PAX`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`PAX` ;

CREATE TABLE IF NOT EXISTS CRS.`PAX`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PNR_ID` INT NOT NULL,
  `성별 코드_CODE` INT NOT NULL,
  `국적코드` INT NOT NULL,
  `체류지 코드` INT NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  `핸드폰번호` VARCHAR(45) NOT NULL,
  `생년월일` VARCHAR(45) NOT NULL,
  `이메일` VARCHAR(45) NULL,
  `연령 구분 코드_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `PNR_ID`),
  INDEX `fk_PAX_PNR1_idx` (`PNR_ID` ASC) VISIBLE,
  INDEX `fk_PAX_성별 코드1_idx` (`성별 코드_CODE` ASC) VISIBLE,
  INDEX `fk_PAX_국적코드1_idx` (`국적코드` ASC) VISIBLE,
  INDEX `fk_PAX_체류지 코드1_idx` (`체류지 코드` ASC) VISIBLE,
  INDEX `fk_PAX_연령 구분 코드1_idx` (`연령 구분 코드_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PAX_PNR1`
    FOREIGN KEY (`PNR_ID`)
    REFERENCES CRS.`PNR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAX_성별 코드1`
    FOREIGN KEY (`성별 코드_CODE`)
    REFERENCES CRS.`성별_코드` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAX_국적코드1`
    FOREIGN KEY (`국적코드`)
    REFERENCES CRS.`국적코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAX_체류지 코드1`
    FOREIGN KEY (`체류지 코드`)
    REFERENCES CRS.`체류지_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAX_연령 구분 코드1`
    FOREIGN KEY (`연령 구분 코드_ID`)
    REFERENCES CRS.`연령_구분_코드` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`항공사`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`항공사` ;

CREATE TABLE IF NOT EXISTS CRS.`항공사`(
  `ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`비행기`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`비행기` ;

CREATE TABLE IF NOT EXISTS CRS.`비행기`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `항공사_ID` INT(11) NOT NULL,
  `비행기 모델` VARCHAR(45) NOT NULL,
  `구매일자` DATETIME NOT NULL,
  PRIMARY KEY (`ID`, `항공사_ID`),
  INDEX `fk_비행기_항공사1_idx` (`항공사_ID` ASC) VISIBLE,
  CONSTRAINT `fk_비행기_항공사1`
    FOREIGN KEY (`항공사_ID`)
    REFERENCES CRS.`항공사` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`좌석_상세_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`좌석_상세_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`좌석_상세_코드`(
  `ID` INT NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`비행기_좌석`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`비행기_좌석` ;

CREATE TABLE IF NOT EXISTS CRS.`비행기_좌석`(
  `좌석 번호` INT NOT NULL,
  `비행기_ID` INT NOT NULL,
  `좌석 상세 코드_ID` INT NOT NULL,
  PRIMARY KEY (`좌석 번호`, `비행기_ID`, `좌석 상세 코드_ID`),
  INDEX `fk_비행기 좌석_좌석 상세 코드1_idx` (`좌석 상세 코드_ID` ASC) VISIBLE,
  CONSTRAINT `fk_비행기 좌석_비행기1`
    FOREIGN KEY (`비행기_ID`)
    REFERENCES CRS.`비행기` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_비행기 좌석_좌석 상세 코드1`
    FOREIGN KEY (`좌석 상세 코드_ID`)
    REFERENCES CRS.`좌석_상세_코드` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`티켓`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`티켓` ;

CREATE TABLE IF NOT EXISTS CRS.`티켓`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PAX_ID` INT NOT NULL,
  `비행기_좌석_좌석 번호` INT NOT NULL,
  PRIMARY KEY (`ID`, `PAX_ID`),
  INDEX `fk_티켓_PAX1_idx` (`PAX_ID` ASC) VISIBLE,
  INDEX `fk_티켓_비행기_좌석1_idx` (`비행기_좌석_좌석 번호` ASC) VISIBLE,
  CONSTRAINT `fk_티켓_PAX1`
    FOREIGN KEY (`PAX_ID`)
    REFERENCES CRS.`PAX` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_티켓_비행기_좌석1`
    FOREIGN KEY (`비행기_좌석_좌석 번호`)
    REFERENCES CRS.`비행기_좌석` (`좌석 번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`국제_국내_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`국제_국내_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`국제_국내_코드`(
  `코드` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`운임종류_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운임종류_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`운임종류_코드`(
  `코드` INT NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`운임금액_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운임금액_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`운임금액_코드`(
  `코드` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`노선구분_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`노선구분_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`노선구분_코드`(
  `코드` INT NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`운임`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운임` ;

CREATE TABLE IF NOT EXISTS CRS.`운임`(
  `ID` INT NOT NULL,
  `국제/국내 코드` INT NOT NULL,
  `운임종류 코드` INT NOT NULL,
  `노선구분 코드` INT NOT NULL,
  `운임금액 코드` INT NOT NULL,
  `운임가격` INT NOT NULL,
  PRIMARY KEY (`ID`, `국제/국내 코드`, `운임종류 코드`, `노선구분 코드`, `운임금액 코드`),
  INDEX `fk_운임_운임종류 분류1 코드1_idx` (`국제/국내 코드` ASC) VISIBLE,
  INDEX `fk_운임_운임종류 분류2 코드1_idx` (`운임종류 코드` ASC) VISIBLE,
  INDEX `fk_운임_운임종류 분류4 코드1_idx` (`운임금액 코드` ASC) VISIBLE,
  INDEX `fk_운임_노선구분 코드1_idx` (`노선구분 코드` ASC) VISIBLE,
  CONSTRAINT `fk_운임_운임종류 분류1 코드1`
    FOREIGN KEY (`국제/국내 코드`)
    REFERENCES CRS.`국제_국내_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_운임_운임종류 분류2 코드1`
    FOREIGN KEY (`운임종류 코드`)
    REFERENCES CRS.`운임종류_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_운임_운임종류 분류4 코드1`
    FOREIGN KEY (`운임금액 코드`)
    REFERENCES CRS.`운임금액_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_운임_노선구분 코드1`
    FOREIGN KEY (`노선구분 코드`)
    REFERENCES CRS.`노선구분_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`세금`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`세금` ;

CREATE TABLE IF NOT EXISTS CRS.`세금`(
  `운임_ID` INT NOT NULL,
  `세금가격` INT NOT NULL,
  PRIMARY KEY (`운임_ID`),
  INDEX `fk_세금_운임1_idx` (`운임_ID` ASC) VISIBLE,
  CONSTRAINT `fk_세금_운임1`
    FOREIGN KEY (`운임_ID`)
    REFERENCES CRS.`운임` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`결제수단코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`결제수단코드` ;

CREATE TABLE IF NOT EXISTS CRS.`결제수단코드`(
  `코드` INT NOT NULL AUTO_INCREMENT,
  `이름` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`결제수단`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`결제수단` ;

CREATE TABLE IF NOT EXISTS CRS.`결제수단`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `티켓_ID` INT NOT NULL,
  `결제수단코드` INT NOT NULL,
  `결제금액` INT NOT NULL,
  PRIMARY KEY (`ID`, `티켓_ID`, `결제수단코드`),
  INDEX `fk_결제수단_결제수단코드1_idx` (`결제수단코드` ASC) VISIBLE,
  INDEX `fk_결제수단_티켓1_idx` (`티켓_ID` ASC) VISIBLE,
  CONSTRAINT `fk_결제수단_결제수단코드1`
    FOREIGN KEY (`결제수단코드`)
    REFERENCES CRS.`결제수단코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_결제수단_티켓1`
    FOREIGN KEY (`티켓_ID`)
    REFERENCES CRS.`티켓` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`쿠폰`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`쿠폰` ;

CREATE TABLE IF NOT EXISTS CRS.`쿠폰`(
  `ID` INT NOT NULL,
  `쿠폰 이름` VARCHAR(45) NULL,
  `할인율` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`부가서비스_내역`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`부가서비스_내역` ;

CREATE TABLE IF NOT EXISTS CRS.`부가서비스_내역`(
  `티켓_ID` INT NOT NULL,
  `티켓_PAX_ID` INT NOT NULL,
  `상품_ID` INT NOT NULL,
  INDEX `fk_부가서비스 내역_티켓1_idx` (`티켓_ID` ASC, `티켓_PAX_ID` ASC) VISIBLE,
  PRIMARY KEY (`티켓_ID`, `티켓_PAX_ID`, `상품_ID`),
  INDEX `fk_부가서비스 내역_상품1_idx` (`상품_ID` ASC) VISIBLE,
  CONSTRAINT `fk_부가서비스 내역_티켓1`
    FOREIGN KEY (`티켓_ID` , `티켓_PAX_ID`)
    REFERENCES CRS.`티켓` (`ID` , `PAX_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_부가서비스 내역_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`환불`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`환불` ;

CREATE TABLE IF NOT EXISTS CRS.`환불`(
  `티켓_ID` INT NOT NULL,
  PRIMARY KEY (`티켓_ID`),
  INDEX `fk_환불_티켓1_idx` (`티켓_ID` ASC) VISIBLE,
  CONSTRAINT `fk_환불_티켓1`
    FOREIGN KEY (`티켓_ID`)
    REFERENCES CRS.`티켓` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`환불결제수단`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`환불결제수단` ;

CREATE TABLE IF NOT EXISTS CRS.`환불결제수단`(
  `ID` INT NOT NULL,
  `환불_티켓_ID` INT NOT NULL,
  `결제수단_ID` INT NOT NULL,
  `금액` INT NOT NULL,
  PRIMARY KEY (`ID`, `환불_티켓_ID`, `결제수단_ID`),
  INDEX `fk_환불결제수단_환불1_idx` (`환불_티켓_ID` ASC) VISIBLE,
  INDEX `fk_환불결제수단_결제수단1_idx` (`결제수단_ID` ASC) VISIBLE,
  CONSTRAINT `fk_환불결제수단_환불1`
    FOREIGN KEY (`환불_티켓_ID`)
    REFERENCES CRS.`환불` (`티켓_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_환불결제수단_결제수단1`
    FOREIGN KEY (`결제수단_ID`)
    REFERENCES CRS.`결제수단` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`환불세금`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`환불세금` ;

CREATE TABLE IF NOT EXISTS CRS.`환불세금`(
  `ID` INT NOT NULL,
  `환불_티켓_ID` INT NOT NULL,
  `세금_운임_ID` INT NOT NULL,
  `금액` INT NOT NULL,
  PRIMARY KEY (`ID`, `환불_티켓_ID`, `세금_운임_ID`),
  INDEX `fk_환불세금_환불1_idx` (`환불_티켓_ID` ASC) VISIBLE,
  INDEX `fk_환불세금_세금1_idx` (`세금_운임_ID` ASC) VISIBLE,
  CONSTRAINT `fk_환불세금_환불1`
    FOREIGN KEY (`환불_티켓_ID`)
    REFERENCES CRS.`환불` (`티켓_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_환불세금_세금1`
    FOREIGN KEY (`세금_운임_ID`)
    REFERENCES CRS.`세금` (`운임_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`환불운임`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`환불운임` ;

CREATE TABLE IF NOT EXISTS CRS.`환불운임`(
  `ID` INT NOT NULL,
  `환불_티켓_ID` INT NOT NULL,
  `운임_ID` INT NOT NULL,
  `금액` INT NOT NULL,
  PRIMARY KEY (`환불_티켓_ID`, `운임_ID`, `ID`),
  INDEX `fk_환불운임_환불1_idx` (`환불_티켓_ID` ASC) VISIBLE,
  INDEX `fk_환불운임_운임1_idx` (`운임_ID` ASC) VISIBLE,
  CONSTRAINT `fk_환불운임_환불1`
    FOREIGN KEY (`환불_티켓_ID`)
    REFERENCES CRS.`환불` (`티켓_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_환불운임_운임1`
    FOREIGN KEY (`운임_ID`)
    REFERENCES CRS.`운임` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`지역구분코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`지역구분코드` ;

CREATE TABLE IF NOT EXISTS CRS.`지역구분코드`(
  `코드` INT NOT NULL,
  `대륙` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`공항`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`공항` ;

CREATE TABLE IF NOT EXISTS CRS.`공항`(
  `ID` VARCHAR(45) NOT NULL,
  `지역구분코드` INT NOT NULL,
  `IATA` VARCHAR(3) NOT NULL,
  `공항이름` VARCHAR(45) NULL,
  `부모 공항` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_공항_공항1_idx` (`부모 공항` ASC) VISIBLE,
  INDEX `fk_공항_한국 및 대륙 구분 코드1_idx` (`지역구분코드` ASC) VISIBLE,
  CONSTRAINT `fk_공항_공항1`
    FOREIGN KEY (`부모 공항`)
    REFERENCES CRS.`공항` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_공항_한국 및 대륙 구분 코드1`
    FOREIGN KEY (`지역구분코드`)
    REFERENCES CRS.`지역구분코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`선호비행정보`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`선호비행정보` ;

CREATE TABLE IF NOT EXISTS CRS.`선호비행정보`(
  `고객_ID` INT NOT NULL,
  `공항_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`고객_ID`, `공항_ID`),
  INDEX `fk_선호비행정보_공항1_idx` (`공항_ID` ASC) VISIBLE,
  INDEX `fk_선호비행정보_고객1_idx` (`고객_ID` ASC) VISIBLE,
  CONSTRAINT `fk_선호비행정보_공항1`
    FOREIGN KEY (`공항_ID`)
    REFERENCES CRS.`공항` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_선호비행정보_고객1`
    FOREIGN KEY (`고객_ID`)
    REFERENCES CRS.`고객` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`신분증_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`신분증_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`신분증_코드`(
  `CODE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`고객식별`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`고객식별` ;

CREATE TABLE IF NOT EXISTS CRS.`고객식별`(
  `고객_ID` INT NOT NULL,
  `신분증 코드_CODE` INT NOT NULL,
  `ID_VALUE` VARCHAR(45) NULL,
  PRIMARY KEY (`고객_ID`, `신분증 코드_CODE`),
  INDEX `fk_고객식별_고객1_idx` (`고객_ID` ASC) VISIBLE,
  INDEX `fk_고객식별_고객식별코드1_idx` (`신분증 코드_CODE` ASC) VISIBLE,
  CONSTRAINT `fk_고객식별_고객1`
    FOREIGN KEY (`고객_ID`)
    REFERENCES CRS.`고객` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_고객식별_고객식별코드1`
    FOREIGN KEY (`신분증 코드_CODE`)
    REFERENCES CRS.`신분증_코드` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`개인`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`개인` ;

CREATE TABLE IF NOT EXISTS CRS.`개인`(
  `고객_ID` INT NOT NULL,
  `성별_코드` INT NOT NULL,
  `이름` VARCHAR(45) NULL,
  `영어이름` VARCHAR(45) NULL,
  `국적코드` INT NULL,
  `이메일` VARCHAR(45) NULL,
  `전화번호` VARCHAR(45) NULL,
  `생년월일` VARCHAR(45) NULL,
  PRIMARY KEY (`고객_ID`),
  INDEX `fk_개인_GENDER_CODE1_idx` (`성별_코드` ASC) VISIBLE,
  INDEX `fk_개인_국적코드1_idx` (`국적코드` ASC) VISIBLE,
  CONSTRAINT `fk_개인_고객1`
    FOREIGN KEY (`고객_ID`)
    REFERENCES CRS.`고객` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_개인_GENDER_CODE1`
    FOREIGN KEY (`성별_코드`)
    REFERENCES CRS.`성별_코드` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_개인_국적코드1`
    FOREIGN KEY (`국적코드`)
    REFERENCES CRS.`국적코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`법인우대_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`법인우대_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`법인우대_코드`(
  `코드` INT NOT NULL AUTO_INCREMENT,
  `이름` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`법인우대혜택`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`법인우대혜택` ;

CREATE TABLE IF NOT EXISTS CRS.`법인우대혜택`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `국제/국내 코드` INT NOT NULL,
  `법인우대 코드` INT NOT NULL,
  `할인율` VARCHAR(45) NULL,
  `적립율` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `국제/국내 코드`, `법인우대 코드`),
  INDEX `fk_법인우대혜택_국제/국내 코드1_idx` (`국제/국내 코드` ASC) VISIBLE,
  INDEX `fk_법인우대혜택_법인우대 코드1_idx` (`법인우대 코드` ASC) VISIBLE,
  CONSTRAINT `fk_법인우대혜택_국제/국내 코드1`
    FOREIGN KEY (`국제/국내 코드`)
    REFERENCES CRS.`국제_국내_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_법인우대혜택_법인우대 코드1`
    FOREIGN KEY (`법인우대 코드`)
    REFERENCES CRS.`법인우대_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`법인고객`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`법인고객` ;

CREATE TABLE IF NOT EXISTS CRS.`법인고객`(
  `고객_ID` INT NOT NULL,
  `법인우대혜택_ID` INT NOT NULL,
  `회사이름` VARCHAR(45) NULL,
  `대표자전화번호` VARCHAR(45) NULL,
  `대표자이메일` VARCHAR(45) NULL,
  PRIMARY KEY (`고객_ID`),
  INDEX `fk_법인고객_법인우대혜택1_idx` (`법인우대혜택_ID` ASC) VISIBLE,
  CONSTRAINT `fk_법인고객_고객1`
    FOREIGN KEY (`고객_ID`)
    REFERENCES CRS.`고객` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_법인고객_법인우대혜택1`
    FOREIGN KEY (`법인우대혜택_ID`)
    REFERENCES CRS.`법인우대혜택` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`법인고객직원`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`법인고객직원` ;

CREATE TABLE IF NOT EXISTS CRS.`법인고객직원`(
  `개인_고객_ID` INT NOT NULL,
  `법인고객_고객_ID` INT NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`개인_고객_ID`),
  INDEX `fk_법인고객직원_법인고객1_idx` (`법인고객_고객_ID` ASC) VISIBLE,
  CONSTRAINT `fk_법인고객직원_개인1`
    FOREIGN KEY (`개인_고객_ID`)
    REFERENCES CRS.`개인` (`고객_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_법인고객직원_법인고객1`
    FOREIGN KEY (`법인고객_고객_ID`)
    REFERENCES CRS.`법인고객` (`고객_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`간편회원구분코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`간편회원구분코드` ;

CREATE TABLE IF NOT EXISTS CRS.`간편회원구분코드`(
  `CODE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`간편회원`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`간편회원` ;

CREATE TABLE IF NOT EXISTS CRS.`간편회원`(
  `개인_고객_ID` INT NOT NULL,
  `간편회원구분코드_CODE` INT NOT NULL,
  `인증키` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`개인_고객_ID`, `간편회원구분코드_CODE`),
  INDEX `fk_간편회원_간편회원구분코드1_idx` (`간편회원구분코드_CODE` ASC) VISIBLE,
  UNIQUE INDEX `인증키_UNIQUE` (`인증키` ASC) VISIBLE,
  CONSTRAINT `fk_간편회원_개인1`
    FOREIGN KEY (`개인_고객_ID`)
    REFERENCES CRS.`개인` (`고객_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_간편회원_간편회원구분코드1`
    FOREIGN KEY (`간편회원구분코드_CODE`)
    REFERENCES CRS.`간편회원구분코드` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`정회원`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`정회원` ;

CREATE TABLE IF NOT EXISTS CRS.`정회원`(
  `개인_고객_ID` INT NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`개인_고객_ID`),
  CONSTRAINT `fk_정회원_개인1`
    FOREIGN KEY (`개인_고객_ID`)
    REFERENCES CRS.`개인` (`고객_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`돌발상황_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`돌발상황_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`돌발상황_코드`(
  `CODE` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`시즌구분_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`시즌구분_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`시즌구분_코드`(
  `CODE` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`운항구분_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운항구분_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`운항구분_코드`(
  `CODE` INT(11) NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`운항계획`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운항계획` ;

CREATE TABLE IF NOT EXISTS CRS.`운항계획`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `운항구분_코드` INT(11) NOT NULL,
  `비행기_ID` INT NOT NULL,
  `시즌구분_코드` INT(11) NOT NULL,
  `항공편명` VARCHAR(45) NOT NULL,
  `항공편_판매가능일자` DATETIME NOT NULL,
  `탑승구` INT NOT NULL,
  PRIMARY KEY (`ID`, `운항구분_코드`),
  INDEX `fk_운항계획_운항구분_코드1_idx` (`운항구분_코드` ASC) VISIBLE,
  INDEX `fk_운항계획_시즌구분_코드1_idx` (`시즌구분_코드` ASC) VISIBLE,
  INDEX `fk_운항계획_비행기1_idx` (`비행기_ID` ASC) VISIBLE,
  CONSTRAINT `fk_운항계획_시즌구분_코드1`
    FOREIGN KEY (`시즌구분_코드`)
    REFERENCES CRS.`시즌구분_코드` (`CODE`),
  CONSTRAINT `fk_운항계획_운항구분_코드1`
    FOREIGN KEY (`운항구분_코드`)
    REFERENCES CRS.`운항구분_코드` (`CODE`),
  CONSTRAINT `fk_운항계획_비행기1`
    FOREIGN KEY (`비행기_ID`)
    REFERENCES CRS.`비행기` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`운항경로`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운항경로` ;

CREATE TABLE IF NOT EXISTS CRS.`운항경로`(
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `운항계획_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `운항계획_ID`),
  INDEX `fk_운항경로_운항계획1_idx` (`운항계획_ID` ASC) VISIBLE,
  CONSTRAINT `fk_운항경로_운항계획1`
    FOREIGN KEY (`운항계획_ID`)
    REFERENCES CRS.`운항계획` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`ATC_Advisory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`ATC_Advisory` ;

CREATE TABLE IF NOT EXISTS CRS.`ATC_Advisory`(
  `ID` INT(11) NOT NULL,
  `공항_ID` VARCHAR(45) NOT NULL,
  `돌발상황_코드` INT(11) NOT NULL,
  `운항경로_ID` INT(11) NOT NULL,
  `상황발생일자` DATETIME NOT NULL,
  PRIMARY KEY (`ID`, `공항_ID`, `돌발상황_코드`),
  INDEX `fk_ATC Advisory_돌발상황_코드1_idx` (`돌발상황_코드` ASC) VISIBLE,
  INDEX `fk_ATC Advisory_운항경로1_idx` (`운항경로_ID` ASC) VISIBLE,
  INDEX `fk_ATC Advisory_공항1_idx` (`공항_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ATC Advisory_돌발상황_코드1`
    FOREIGN KEY (`돌발상황_코드`)
    REFERENCES CRS.`돌발상황_코드` (`CODE`),
  CONSTRAINT `fk_ATC Advisory_운항경로1`
    FOREIGN KEY (`운항경로_ID`)
    REFERENCES CRS.`운항경로` (`ID`),
  CONSTRAINT `fk_ATC Advisory_공항1`
    FOREIGN KEY (`공항_ID`)
    REFERENCES CRS.`공항` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`공항_부서`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`공항_부서` ;

CREATE TABLE IF NOT EXISTS CRS.`공항_부서`(
  `ID` INT(11) NOT NULL,
  `이름` VARCHAR(45) NOT NULL,
  `핸드폰_번호` VARCHAR(45) NULL DEFAULT NULL,
  `이메일` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`주소`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`주소` ;

CREATE TABLE IF NOT EXISTS CRS.`주소`(
  `ID` INT(11) NOT NULL,
  `우편번호` VARCHAR(6) NOT NULL,
  `상세주소` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`승무원`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`승무원` ;

CREATE TABLE IF NOT EXISTS CRS.`승무원`(
  `ID` INT(11) NOT NULL,
  `성별 코드` INT NOT NULL,
  `주소_ID` INT(11) NOT NULL,
  `부서_ID` INT(11) NOT NULL,
  `관리자_ID` INT(11) NULL DEFAULT NULL,
  `이름` VARCHAR(45) NOT NULL,
  `생년월일` DATETIME NOT NULL,
  `이메일` VARCHAR(45) NULL DEFAULT NULL,
  `핸드폰_번호` VARCHAR(45) NULL DEFAULT NULL,
  `입사일` DATETIME NULL DEFAULT NULL,
  `퇴사일` DATETIME NULL DEFAULT NULL,
  `임금` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_FLIGHT_ATTENDANT_ADDRESS_idx` (`주소_ID` ASC) VISIBLE,
  INDEX `fk_FLIGHT_ATTENDANT_AIRLINE_DEPARTMENT1_idx` (`부서_ID` ASC) VISIBLE,
  INDEX `fk_FLIGHT_ATTENDANT_FLIGHT_ATTENDANT1_idx` (`관리자_ID` ASC) VISIBLE,
  INDEX `fk_승무원_성별 코드1_idx` (`성별 코드` ASC) VISIBLE,
  CONSTRAINT `fk_FLIGHT_ATTENDANT_ADDRESS`
    FOREIGN KEY (`주소_ID`)
    REFERENCES CRS.`주소` (`ID`),
  CONSTRAINT `fk_FLIGHT_ATTENDANT_AIRLINE_DEPARTMENT1`
    FOREIGN KEY (`부서_ID`)
    REFERENCES CRS.`공항_부서` (`ID`),
  CONSTRAINT `fk_FLIGHT_ATTENDANT_FLIGHT_ATTENDANT1`
    FOREIGN KEY (`관리자_ID`)
    REFERENCES CRS.`승무원` (`ID`),
  CONSTRAINT `fk_승무원_성별 코드1`
    FOREIGN KEY (`성별 코드`)
    REFERENCES CRS.`성별_코드` (`CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`승무원_편조`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`승무원_편조` ;

CREATE TABLE IF NOT EXISTS CRS.`승무원_편조`(
  `ID` INT(11) NOT NULL,
  `승무원_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `승무원_ID`),
  INDEX `fk_승무원_편조_승무원1_idx` (`승무원_ID` ASC) VISIBLE,
  CONSTRAINT `fk_승무원_편조_승무원1`
    FOREIGN KEY (`승무원_ID`)
    REFERENCES CRS.`승무원` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`승무원_비행계획`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`승무원_비행계획` ;

CREATE TABLE IF NOT EXISTS CRS.`승무원_비행계획`(
  `운항계획_ID` INT(11) NOT NULL,
  `승무원_편조_ID` INT(11) NOT NULL,
  `계획` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`운항계획_ID`),
  INDEX `fk_승무원_비행계획_운항계획1_idx` (`운항계획_ID` ASC) VISIBLE,
  INDEX `fk_승무원_비행계획_승무원_편조1_idx` (`승무원_편조_ID` ASC) VISIBLE,
  CONSTRAINT `fk_승무원_비행계획_승무원_편조1`
    FOREIGN KEY (`승무원_편조_ID`)
    REFERENCES CRS.`승무원_편조` (`ID`),
  CONSTRAINT `fk_승무원_비행계획_운항계획1`
    FOREIGN KEY (`운항계획_ID`)
    REFERENCES CRS.`운항계획` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`출도착`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`출도착` ;

CREATE TABLE IF NOT EXISTS CRS.`출도착`(
  `운항계획_ID` INT(11) NOT NULL,
  `운항계획_운항구분_코드` INT(11) NOT NULL,
  `출발공항` VARCHAR(45) NOT NULL,
  `도착공항` VARCHAR(45) NOT NULL,
  `출발일자` DATETIME NOT NULL,
  `도착일자` DATETIME NOT NULL,
  `적립가능_마일리지` INT(11) NOT NULL,
  PRIMARY KEY (`운항계획_ID`, `운항계획_운항구분_코드`),
  INDEX `fk_출도착_공항1_idx` (`출발공항` ASC) VISIBLE,
  INDEX `fk_출도착_공항2_idx` (`도착공항` ASC) VISIBLE,
  CONSTRAINT `fk_출도착_운항계획2`
    FOREIGN KEY (`운항계획_ID` , `운항계획_운항구분_코드`)
    REFERENCES CRS.`운항계획` (`ID` , `운항구분_코드`),
  CONSTRAINT `fk_출도착_공항1`
    FOREIGN KEY (`출발공항`)
    REFERENCES CRS.`공항` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_출도착_공항2`
    FOREIGN KEY (`도착공항`)
    REFERENCES CRS.`공항` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `CRS`.`혜택 코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`혜택 코드` ;

CREATE TABLE IF NOT EXISTS CRS.`혜택 코드`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`SEG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`SEG` ;

CREATE TABLE IF NOT EXISTS CRS.`SEG`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PNR_ID` INT NOT NULL,
  `혜택 코드_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `PNR_ID`),
  INDEX `fk_SEG_PNR1_idx` (`PNR_ID` ASC) VISIBLE,
  INDEX `fk_SEG_직원 그룹 코드1_idx` (`혜택 코드_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SEG_PNR1`
    FOREIGN KEY (`PNR_ID`)
    REFERENCES CRS.`PNR` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SEG_직원 그룹 코드1`
    FOREIGN KEY (`혜택 코드_ID`)
    REFERENCES CRS.`혜택 코드` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`SSR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`SSR` ;

CREATE TABLE IF NOT EXISTS CRS.`SSR`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `SEG_ID` INT NOT NULL,
  `SEG_PNR_ID` INT NOT NULL,
  `PAX_ID` INT NOT NULL,
  `PAX_PNR_ID` INT NOT NULL,
  `요청사항` TEXT NOT NULL,
  PRIMARY KEY (`ID`, `SEG_ID`, `SEG_PNR_ID`, `PAX_ID`, `PAX_PNR_ID`),
  INDEX `fk_SSR_SEG1_idx` (`SEG_ID` ASC, `SEG_PNR_ID` ASC) VISIBLE,
  INDEX `fk_SSR_PAX1_idx` (`PAX_ID` ASC, `PAX_PNR_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SSR_SEG1`
    FOREIGN KEY (`SEG_ID` , `SEG_PNR_ID`)
    REFERENCES CRS.`SEG` (`ID` , `PNR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SSR_PAX1`
    FOREIGN KEY (`PAX_ID` , `PAX_PNR_ID`)
    REFERENCES CRS.`PAX` (`ID` , `PNR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`부가서비스_예약내역`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`부가서비스_예약내역` ;

CREATE TABLE IF NOT EXISTS CRS.`부가서비스_예약내역`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `상품_ID` INT NOT NULL,
  `SEG_ID` INT NOT NULL,
  `SEG_PNR_ID` INT NOT NULL,
  `PAX_ID` INT NOT NULL,
  `PAX_PNR_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `SEG_ID`, `SEG_PNR_ID`, `PAX_ID`, `PAX_PNR_ID`, `상품_ID`),
  INDEX `fk_부가서비스 예약내역_SEG1_idx` (`SEG_ID` ASC, `SEG_PNR_ID` ASC) VISIBLE,
  INDEX `fk_부가서비스 예약내역_PAX1_idx` (`PAX_ID` ASC, `PAX_PNR_ID` ASC) VISIBLE,
  INDEX `fk_부가서비스 예약내역_상품1_idx` (`상품_ID` ASC) VISIBLE,
  CONSTRAINT `fk_부가서비스 예약내역_SEG1`
    FOREIGN KEY (`SEG_ID` , `SEG_PNR_ID`)
    REFERENCES CRS.`SEG` (`ID` , `PNR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_부가서비스 예약내역_PAX1`
    FOREIGN KEY (`PAX_ID` , `PAX_PNR_ID`)
    REFERENCES CRS.`PAX` (`ID` , `PNR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_부가서비스 예약내역_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`쿠폰사용`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`쿠폰사용` ;

CREATE TABLE IF NOT EXISTS CRS.`쿠폰사용`(
  `티켓_ID` INT NOT NULL,
  `쿠폰_ID` INT NOT NULL,
  PRIMARY KEY (`티켓_ID`, `쿠폰_ID`),
  INDEX `fk_쿠폰사용_쿠폰1_idx` (`쿠폰_ID` ASC) VISIBLE,
  CONSTRAINT `fk_쿠폰사용_티켓1`
    FOREIGN KEY (`티켓_ID`)
    REFERENCES CRS.`티켓` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_쿠폰사용_쿠폰1`
    FOREIGN KEY (`쿠폰_ID`)
    REFERENCES CRS.`쿠폰` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`SEG가_보유한_쿠폰`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`SEG가_보유한_쿠폰` ;

CREATE TABLE IF NOT EXISTS CRS.`SEG가_보유한_쿠폰`(
  `쿠폰_ID` INT NOT NULL,
  `SEG_ID` INT NOT NULL,
  `보유 개수` INT NULL,
  PRIMARY KEY (`쿠폰_ID`),
  INDEX `fk_SEG가 보유한 쿠폰_쿠폰1_idx` (`쿠폰_ID` ASC) VISIBLE,
  INDEX `fk_SEG가 보유한 쿠폰_SEG1_idx` (`SEG_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SEG가 보유한 쿠폰_쿠폰1`
    FOREIGN KEY (`쿠폰_ID`)
    REFERENCES CRS.`쿠폰` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SEG가 보유한 쿠폰_SEG1`
    FOREIGN KEY (`SEG_ID`)
    REFERENCES CRS.`SEG` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`항공권`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`항공권` ;

CREATE TABLE IF NOT EXISTS CRS.`항공권`(
  `상품_ID` INT NOT NULL AUTO_INCREMENT,
  `운임_ID` INT NOT NULL,
  `운항계획_ID` INT(11) NOT NULL,
  PRIMARY KEY (`상품_ID`),
  INDEX `fk_항공권_운임1_idx` (`운임_ID` ASC) VISIBLE,
  INDEX `fk_항공권_운항계획1_idx` (`운항계획_ID` ASC) VISIBLE,
  CONSTRAINT `fk_항공권_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_항공권_운임1`
    FOREIGN KEY (`운임_ID`)
    REFERENCES CRS.`운임` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_항공권_운항계획1`
    FOREIGN KEY (`운항계획_ID`)
    REFERENCES CRS.`운항계획` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`부가서비스`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`부가서비스` ;

CREATE TABLE IF NOT EXISTS CRS.`부가서비스`(
  `상품_ID` INT NOT NULL AUTO_INCREMENT,
  `항공권_상품_ID` INT NOT NULL,
  PRIMARY KEY (`상품_ID`),
  INDEX `fk_부가서비스_항공권1_idx` (`항공권_상품_ID` ASC) VISIBLE,
  CONSTRAINT `fk_부가서비스_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_부가서비스_항공권1`
    FOREIGN KEY (`항공권_상품_ID`)
    REFERENCES CRS.`항공권` (`상품_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`제휴상품_종류`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`제휴상품_종류` ;

CREATE TABLE IF NOT EXISTS CRS.`제휴상품_종류`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `종류` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`제휴고객사`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`제휴고객사` ;

CREATE TABLE IF NOT EXISTS CRS.`제휴고객사`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `회사이름` VARCHAR(45) NOT NULL,
  `제휴상품 종류_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_제휴고객사_제휴상품 종류1_idx` (`제휴상품 종류_ID` ASC) VISIBLE,
  CONSTRAINT `fk_제휴고객사_제휴상품 종류1`
    FOREIGN KEY (`제휴상품 종류_ID`)
    REFERENCES CRS.`제휴상품_종류` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`제휴상품`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`제휴상품` ;

CREATE TABLE IF NOT EXISTS CRS.`제휴상품`(
  `상품_ID` INT NOT NULL AUTO_INCREMENT,
  `제휴고객사_ID` INT NOT NULL,
  `혜택정보` VARCHAR(200) NOT NULL,
  `시작일자` DATETIME NOT NULL,
  `종료일자` DATETIME NOT NULL,
  PRIMARY KEY (`상품_ID`),
  INDEX `fk_제휴상품_제휴고객사1_idx` (`제휴고객사_ID` ASC) VISIBLE,
  CONSTRAINT `fk_제휴상품_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_제휴상품_제휴고객사1`
    FOREIGN KEY (`제휴고객사_ID`)
    REFERENCES CRS.`제휴고객사` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`액세서리_종류_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`액세서리_종류_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`액세서리_종류_코드`(
  `코드` INT NOT NULL AUTO_INCREMENT,
  `이름` VARCHAR(45) NOT NULL,
  `금액` VARCHAR(45) NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`액세서리`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`액세서리` ;

CREATE TABLE IF NOT EXISTS CRS.`액세서리`(
  `상품_ID` INT NOT NULL AUTO_INCREMENT,
  `액세서리_종류_코드` INT NOT NULL,
  PRIMARY KEY (`상품_ID`),
  INDEX `fk_액세서리_액세서리 종류 코드1_idx` (`액세서리_종류_코드` ASC) VISIBLE,
  CONSTRAINT `fk_액세서리_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_액세서리_액세서리 종류 코드1`
    FOREIGN KEY (`액세서리_종류_코드`)
    REFERENCES CRS.`액세서리_종류_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`결합상품`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`결합상품` ;

CREATE TABLE IF NOT EXISTS CRS.`결합상품`(
  `상품_ID` INT NOT NULL AUTO_INCREMENT,
  `설명` TEXT NULL,
  `총_가격` INT NULL,
  PRIMARY KEY (`상품_ID`),
  CONSTRAINT `fk_결합상품_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`구매방법 코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`구매방법 코드` ;

CREATE TABLE IF NOT EXISTS CRS.`구매방법 코드`(
  `코드` INT NOT NULL AUTO_INCREMENT,
  `구매방법` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`수하물_금액표`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`수하물_금액표` ;

CREATE TABLE IF NOT EXISTS CRS.`수하물_금액표`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `무게(kg)` INT NOT NULL,
  `금액` INT NOT NULL,
  `구매방법 코드` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_수하물 금액_구매방법 코드1_idx` (`구매방법 코드` ASC) VISIBLE,
  CONSTRAINT `fk_수하물 금액_구매방법 코드1`
    FOREIGN KEY (`구매방법 코드`)
    REFERENCES CRS.`구매방법 코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`식사_및_음료_종류`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`식사_및_음료_종류` ;

CREATE TABLE IF NOT EXISTS CRS.`식사_및_음료_종류`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `종류` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`메뉴`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`메뉴` ;

CREATE TABLE IF NOT EXISTS CRS.`메뉴`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `이름` VARCHAR(45) NOT NULL,
  `금액` VARCHAR(45) NOT NULL,
  `식사 종류_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_메뉴_식사 종류1_idx` (`식사 종류_ID` ASC) VISIBLE,
  CONSTRAINT `fk_메뉴_식사 종류1`
    FOREIGN KEY (`식사 종류_ID`)
    REFERENCES CRS.`식사_및_음료_종류` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`기내식`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`기내식` ;

CREATE TABLE IF NOT EXISTS CRS.`기내식`(
  `부가서비스_상품_ID` INT NOT NULL,
  `메뉴_ID` INT NOT NULL,
  PRIMARY KEY (`부가서비스_상품_ID`),
  INDEX `fk_기내식_메뉴1_idx` (`메뉴_ID` ASC) VISIBLE,
  CONSTRAINT `fk_기내식_부가서비스1`
    FOREIGN KEY (`부가서비스_상품_ID`)
    REFERENCES CRS.`부가서비스` (`상품_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_기내식_메뉴1`
    FOREIGN KEY (`메뉴_ID`)
    REFERENCES CRS.`메뉴` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`수하물_출도착지_코드`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`수하물_출도착지_코드` ;

CREATE TABLE IF NOT EXISTS CRS.`수하물_출도착지_코드`(
  `코드` INT NOT NULL AUTO_INCREMENT,
  `국가` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`코드`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`국가별_수하물_금액`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`국가별_수하물_금액` ;

CREATE TABLE IF NOT EXISTS CRS.`국가별_수하물_금액`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `수하물 출발지 코드` INT NOT NULL,
  `수하물 도착지 코드` INT NOT NULL,
  `수하물 금액_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_수화물 금액_수하물 출도착지 코드1_idx` (`수하물 출발지 코드` ASC) VISIBLE,
  INDEX `fk_수화물 금액_수하물 출도착지 코드2_idx` (`수하물 도착지 코드` ASC) VISIBLE,
  INDEX `fk_수화물 금액_수하물 금액1_idx` (`수하물 금액_ID` ASC) VISIBLE,
  CONSTRAINT `fk_수화물 금액_수하물 출도착지 코드1`
    FOREIGN KEY (`수하물 출발지 코드`)
    REFERENCES CRS.`수하물_출도착지_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_수화물 금액_수하물 출도착지 코드2`
    FOREIGN KEY (`수하물 도착지 코드`)
    REFERENCES CRS.`수하물_출도착지_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_수화물 금액_수하물 금액1`
    FOREIGN KEY (`수하물 금액_ID`)
    REFERENCES CRS.`수하물_금액표` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`수하물`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`수하물` ;

CREATE TABLE IF NOT EXISTS CRS.`수하물`(
  `부가서비스_상품_ID` INT NOT NULL AUTO_INCREMENT,
  `국가별 수하물 금액_ID` INT NOT NULL,
  PRIMARY KEY (`부가서비스_상품_ID`),
  INDEX `fk_수하물_국가별 수하물 금액1_idx` (`국가별 수하물 금액_ID` ASC) VISIBLE,
  CONSTRAINT `fk_수하물_부가서비스1`
    FOREIGN KEY (`부가서비스_상품_ID`)
    REFERENCES CRS.`부가서비스` (`상품_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_수하물_국가별 수하물 금액1`
    FOREIGN KEY (`국가별 수하물 금액_ID`)
    REFERENCES CRS.`국가별_수하물_금액` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`좌석`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`좌석` ;

CREATE TABLE IF NOT EXISTS CRS.`좌석`(
  `부가서비스_상품_ID` INT NOT NULL,
  `금액` INT NOT NULL,
  `비행기_좌석_좌석 번호` INT NOT NULL,
  PRIMARY KEY (`부가서비스_상품_ID`),
  INDEX `fk_좌석_비행기_좌석1_idx` (`비행기_좌석_좌석 번호` ASC) VISIBLE,
  CONSTRAINT `fk_좌석_부가서비스1`
    FOREIGN KEY (`부가서비스_상품_ID`)
    REFERENCES CRS.`부가서비스` (`상품_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_좌석_비행기_좌석1`
    FOREIGN KEY (`비행기_좌석_좌석 번호`)
    REFERENCES CRS.`비행기_좌석` (`좌석 번호`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`운임_종류별_혜택`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`운임_종류별_혜택` ;

CREATE TABLE IF NOT EXISTS CRS.`운임_종류별_혜택`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `운임종류 코드` INT NOT NULL,
  `기내수하물 무게` INT NOT NULL,
  `리프레시 포인트` INT NOT NULL,
  `위탁수하물 무게` INT NOT NULL,
  `기내식 제공 여부` TINYINT NOT NULL,
  `우선 탑승 여부` TINYINT NOT NULL,
  `우선 체크인 여부` TINYINT NOT NULL,
  `우선 수하물 처리 여부` TINYINT NOT NULL,
  PRIMARY KEY (`ID`, `운임종류 코드`),
  INDEX `fk_운임 종류별 혜택_운임종류 코드1_idx` (`운임종류 코드` ASC) VISIBLE,
  CONSTRAINT `fk_운임 종류별 혜택_운임종류 코드1`
    FOREIGN KEY (`운임종류 코드`)
    REFERENCES CRS.`운임종류_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`결합상품_구성상세`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`결합상품_구성상세` ;

CREATE TABLE IF NOT EXISTS CRS.`결합상품_구성상세`(
  `결합상품_상품_ID` INT NOT NULL AUTO_INCREMENT,
  `상품_ID` INT NOT NULL,
  PRIMARY KEY (`결합상품_상품_ID`, `상품_ID`),
  INDEX `fk_table1_상품1_idx` (`상품_ID` ASC) VISIBLE,
  CONSTRAINT `fk_table1_결합상품1`
    FOREIGN KEY (`결합상품_상품_ID`)
    REFERENCES CRS.`결합상품` (`상품_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_상품1`
    FOREIGN KEY (`상품_ID`)
    REFERENCES CRS.`상품` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRS`.`좌석_운행_구분`
-- -----------------------------------------------------
DROP TABLE IF EXISTS CRS.`좌석_운행_구분` ;

CREATE TABLE IF NOT EXISTS CRS.`좌석_운행_구분`(
  `운임종류_코드` INT NOT NULL,
  `좌석_상세_코드` INT NOT NULL,
  INDEX `fk_좌석_운행_구분_코드_운임종류_코드1_idx` (`운임종류_코드` ASC) VISIBLE,
  PRIMARY KEY (`운임종류_코드`, `좌석_상세_코드`),
  INDEX `fk_좌석_운행_구분_코드_좌석_상세_코드1_idx` (`좌석_상세_코드` ASC) VISIBLE,
  CONSTRAINT `fk_좌석_운행_구분_코드_운임종류_코드1`
    FOREIGN KEY (`운임종류_코드`)
    REFERENCES CRS.`운임종류_코드` (`코드`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_좌석_운행_구분_코드_좌석_상세_코드1`
    FOREIGN KEY (`좌석_상세_코드`)
    REFERENCES CRS.`좌석_상세_코드` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
